import { describe, test, expect, mock, beforeEach } from "bun:test";
import { ChatSessionService } from "../../../services/chatSession/chatSessionService";
import type { ChatSessionData, ChatSessionStore } from "../../../services/chatSession/types";
import type { LLMMessage, LLMProvider } from "../../../services/llm/types";
import { ChatSession } from "../../../services/chatSession/chatSession";

describe("ChatSessionService Unit Tests", () => {
  let mockStore: ChatSessionStore;
  let mockProvider: LLMProvider;
  let service: ChatSessionService;

  beforeEach(() => {
    // 1. Setup mock database/storage layer
    const storeState = new Map<string, ChatSessionData>();
    mockStore = {
      save: mock(async (session: ChatSessionData) => {
        storeState.set(session.id, session);
      }),
      get: mock(async (id: string) => {
        return storeState.get(id) ?? null;
      }),
      delete: mock(async (id: string) => {
        storeState.delete(id);
      }),
    };

    // 2. Setup mock LLM provider layer
    mockProvider = {
        name: "groq", // Use an actual valid name from your LLMProviderName union
        sendMessages: mock(async (messages: LLMMessage[], options?: any) => {
        return "Mocked LLM Response";
        }),
        sendText: mock(async (prompt: string, options?: any) => {
        return "Mocked Text Response";
        }),
    } as unknown as LLMProvider;

    // 3. Inject mocks via constructor dependency injection
    service = new ChatSessionService(mockProvider, mockStore);
  });

  // =========================================================================
  // CREATE SESSION TESTS
  // =========================================================================
  describe("createSession", () => {
    test("should initialize a completely empty session when no options are provided", async () => {
      const session = await service.createSession();

      // Assert instance qualities
      expect(session).toBeInstanceOf(ChatSession);
      expect(session.id).toBeTypeOf("string");
      expect(session.messages).toEqual([]);

      // Assert persistence was triggered correctly
      expect(mockStore.save).toHaveBeenCalledTimes(1);
      const savedData = (mockStore.save as any).mock.calls[0][0];
      expect(savedData.id).toBe(session.id);
      expect(savedData.messages).toEqual([]);
    });

    test("should prepend a system prompt when provided in options", async () => {
      const systemPrompt = "You are an elite debugging assistant.";
      const session = await service.createSession({ systemPrompt });

      const expectedMessages: LLMMessage[] = [
        { role: "system", content: systemPrompt }
      ];

      expect(session.messages).toEqual(expectedMessages);
      
      // Ensure the system message made it into the store record
      const savedData = (mockStore.save as any).mock.calls[0][0];
      expect(savedData.messages).toEqual(expectedMessages);
    });
  });

  // =========================================================================
  // GET / HYDRATION SESSION TESTS
  // =========================================================================
  describe("getSession", () => {
    test("should return null if the session ID does not exist in storage", async () => {
      const result = await service.getSession("non-existent-uuid");
      
      expect(result).toBeNull();
      expect(mockStore.get).toHaveBeenCalledWith("non-existent-uuid");
    });

    test("should successfully hydrate raw store data back into an operational ChatSession instance", async () => {
      const existingData: ChatSessionData = {
        id: "existing-uuid",
        messages: [{ role: "user", content: "Pre-existing historical text" }],
        createdAt: new Date(2023, 1, 1),
        updatedAt: new Date(2023, 1, 2),
      };
      
      // Manually prime our mock store
      await mockStore.save(existingData);

      // Hydrate via service
      const session = await service.getSession("existing-uuid");

      expect(session).toBeInstanceOf(ChatSession);
      expect(session!.id).toBe("existing-uuid");
      expect(session!.messages).toEqual(existingData.messages);
      expect(session!.createdAt).toEqual(existingData.createdAt);
      expect(session!.updatedAt).toEqual(existingData.updatedAt);
    });
  });

  // =========================================================================
  // RUNTIME CONTEXT TESTS (Testing the bridge methods generated by the service)
  // =========================================================================
  describe("Runtime Context Integration", () => {
    test("should accurately route runtime session operations to underlying providers", async () => {
      // 1. Create a live session using the service infrastructure
      const session = await service.createSession();
      
      // 2. Act: Trigger a message dispatch from the isolated session object
      await session.sendMessage("Testing the bridge link");

      // 3. Assert: The session's inner context successfully routed down into our service dependencies
      expect(mockProvider.sendMessages).toHaveBeenCalledTimes(1);
      expect(mockStore.save).toHaveBeenCalledTimes(3); // 1 initialization + 1 user update + 1 assistant update
    });

    test("should reliably handle context deletion commands", async () => {
      const session = await service.createSession();
      
      // Act: Delete directly from the domain model instance
      await session.delete();

      // Assert: Verify erasure calls propagated all the way down to storage tracking
      expect(mockStore.delete).toHaveBeenCalledWith(session.id);
      
      const missingSession = await service.getSession(session.id);
      expect(missingSession).toBeNull();
    });

    test("should preserve original createdAt timestamps during updates inside runtime context", async () => {
      const customPastDate = new Date("2025-01-01T00:00:00.000Z");
      const existingData: ChatSessionData = {
        id: "timestamp-test-id",
        messages: [],
        createdAt: customPastDate,
        updatedAt: customPastDate,
      };
      await mockStore.save(existingData);

      const session = await service.getSession("timestamp-test-id");
      expect(session).not.toBeNull();

      // Send a message to force an operational context .save() transaction
      await session!.sendMessage("Hello world");

      const rawStoredRecord = await mockStore.get("timestamp-test-id");
      
      // The createdAt timestamp should remain untouched, while updatedAt should change to now
      expect(rawStoredRecord!.createdAt).toEqual(customPastDate);
      expect(rawStoredRecord!.updatedAt.getTime()).toBeGreaterThan(customPastDate.getTime());
    });
  });
});